[community]
repos = [
    "forum-theme",
    "go-community",
    "site",
]

[beyond-tp]
repos = [
    "beyond-tp",
    "site",
    "go-toolbox",
]

[go-storage]
repos = [
    "beyond-fs",
    "beyond-ftp",
    "go-coreutils",
    "go-endpoint",
    "go-integration-test",
    "go-storage",
    "go-storage-example",
    "go-service-*",
    "site",
]
