name: "Team Sync"

on: [ push, pull_request ]

jobs:
  team_sync:
    name: Team Sync
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: beyondstorage/go-community
          path: go-community
          ref: v0.2.0

      - name: Build community tools
        working-directory: go-community
        run: make build

      - name: Sync Team
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          COMMUNITY_GITHUB_OWNER: beyondstorage
          COMMUNITY_GITHUB_ACCESS_TOKEN: ${{ secrets.COMMUNITY_GITHUB_ACCESS_TOKEN }}
        run: ./go-community/bin/community team sync --path teams.toml
